streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': ['user://themes/custom-theme', 'user://themes/quark']
enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  'user/themes/custom-theme/images/logo/image 4.svg':
    name: 'image 4.svg'
    full_path: 'image 4.svg'
    type: image/svg+xml
    size: 2854
    path: 'user/themes/custom-theme/images/logo/image 4.svg'
custom_logo_mobile:
  'user/themes/custom-theme/images/logo/image 4.svg':
    name: 'image 4.svg'
    full_path: 'image 4.svg'
    type: image/svg+xml
    size: 2854
    path: 'user/themes/custom-theme/images/logo/image 4.svg'
